---
# tasks file for dj-wasabi.zabbix-proxy

- name: "Set OS dependent variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/main.yml"

- name: "Install the correct repository"
  include: "RedHat.yml"
  when:
    - ansible_os_family == "RedHat"

- name: "Install the correct repository"
  include: "Debian.yml"
  when:
    - ansible_os_family == "Debian"

- name: "Installing the database"
  include: "{{ zabbix_proxy_database_long }}.yml"

- name: "Create include dir zabbix-proxy"
  file:
    path: "{{ zabbix_proxy_include }}"
    owner: zabbix
    group: zabbix
    mode: 0755
    state: directory

- name: "Create module dir zabbix-proxy"
  file:
    path: "{{ zabbix_proxy_loadmodulepath }}"
    owner: zabbix
    group: zabbix
    state: directory

- name: "Create directory for PSK file if not exist."
  file:
    path: "{{ zabbix_proxy_tlspskfile | dirname }}"
    mode: 0755
    state: directory
  become: yes
  when:
    - zabbix_proxy_tlspskfile is defined

- name: "Place TLS PSK File"
  copy:
    dest: "{{ zabbix_proxy_tlspskfile }}"
    content: "{{ zabbix_proxy_tlspsk_secret }}"
    owner: zabbix
    group: zabbix
    mode: 0400
  become: yes
  when:
    - zabbix_proxy_tlspskfile is defined
    - zabbix_proxy_tlspsk_secret is defined
  notify:
    - restart zabbix-proxy

- name: "Allow zabbix_proxy to start (SELinux)"
  selinux_permissive:
    name: zabbix_t
    permissive: true
  become: yes
  when:
    - zabbix_selinux

- name: "Configure zabbix-proxy"
  template:
    src: zabbix_proxy.conf.j2
    dest: /etc/zabbix/zabbix_proxy.conf
    owner: zabbix
    group: zabbix
    mode: 0644
  notify: restart zabbix-proxy

- name: "zabbix-proxy started"
  service:
    name: zabbix-proxy
    state: started
    enabled: yes

- name: "Install local python-netaddr package"
  pip:
    name: netaddr
    state: present
  register: zabbix_python_netaddr_package_installed
  until: zabbix_python_netaddr_package_installed is succeeded
  delegate_to: localhost
  become: "{{ zabbix_proxy_become_on_localhost }}"
  when:
    - zabbix_install_pip_packages
    - ansible_all_ipv4_addresses is defined
    - zabbix_api_create_proxy

- name: "Installing the Zabbix-api package on localhost"
  pip:
    name: zabbix-api
    state: present
  register: zabbix_api_package_installed
  until: zabbix_api_package_installed is succeeded
  delegate_to: localhost
  become: "{{ zabbix_proxy_become_on_localhost }}"
  when:
    - zabbix_install_pip_packages
    - zabbix_api_create_proxy

- name: "Create a new proxy or update an existing host's info"
  zabbix_proxy:
    server_url: "{{ zabbix_url }}"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_pass }}"
    proxy_name: "{{ zabbix_agent_hostname }}"
    description: "{{ zabbix_agent_hostname }}"
    status: "{{ 'active' if zabbix_proxy_mode == 0 else 'passive' }}"
    state: present
    interface: "{{ zabbix_proxy_interface }}"
  when:
    - zabbix_api_create_proxy
  delegate_to: localhost
  become: no
  changed_when: false
  tags:
    - api
